%% Function to calculate i_Far
% The ith index is the faradaic current of the ith CV
function i_Far = iFarCalc( T, Ce_norm, X_AN, X_CA, eta, RT_inv_vec, AN__i_0_ref , AN__alpha_a, AN__alpha_c, CA__i_0_ref, CA__alpha_a, CA__alpha_c, ...
    FLAG__Newman_i_o, CONS__F, ...
    N__CV_Region_AN, N__CV_Region_CA, N__N_CV_SEP, AN__i_oHandle , CA__i_oHandle)

    if FLAG__Newman_i_o
        % i_o_an = CONS__F * AN.k_o ...
        %                     * SV(P__C_Liion     ,N__CV_Region_AN)  .^AN__alpha_a ...
        %   .* ( AN__C_Li_max - SV(P__C_Li_surf_AN,N__CV_Region_AN) ).^AN__alpha_a ...
        %                    .* SV(P__C_Li_surf_AN,N__CV_Region_AN)  .^AN__alpha_c;
        % i_o_ca = CONS__F * CA.k_o ...
        %                     * SV(P__C_Liion     ,N__CV_Region_CA)  .^CA__alpha_a ...
        %   .* ( CA__C_Li_max - SV(P__C_Li_surf_CA,N__CV_Region_CA) ).^CA__alpha_a ...
        %                    .* SV(P__C_Li_surf_CA,N__CV_Region_CA)  .^CA__alpha_c;
    else
        i_o_an  = AN__i_oHandle( T(:,N__CV_Region_AN) , Ce_norm(:,N__CV_Region_AN) , X_AN(end,:) , AN__i_0_ref , AN__alpha_a, AN__alpha_c);
        i_o_ca  = CA__i_oHandle( T(:,N__CV_Region_CA) , Ce_norm(:,N__CV_Region_CA) , X_CA(end,:) , CA__i_0_ref , CA__alpha_a, CA__alpha_c);
    end
    i_o     = [i_o_an, NaN(1,N__N_CV_SEP), i_o_ca];
    
    i_Far = i_o .* ( exp( CA__alpha_a*CONS__F*eta.*RT_inv_vec ) - exp(-CA__alpha_c*CONS__F*eta.*RT_inv_vec ));
end